### ISSUE TITLE
GraphPlot output rendered incorrectly

### ISSUE THREAD

**Issue by gdelfino** [JerryI/wolfram-js-frontend#133]
**Describe the bug**

The 1st example in the Wolfram documentation for the `GraphPlot` command is `GraphPlot[PetersenGraph[]]`. The output is completely different when run from WLJS.

**To Reproduce**

Evaluate `GraphPlot[PetersenGraph[]]` in WLJS

**Expected behavior**

See the 1st example output in https://reference.wolfram.com/language/ref/GraphPlot.html

**Screenshots**

![WLJS-GraphPlot-Bug](https://github.com/JerryI/wolfram-js-frontend/assets/11764/3186e89d-b7b3-4982-836b-80411384cf95)

**Desktop**

 - Windows 10
 - Desktop App

**Comment by JerryI** [comment]
Thank you for your feedback!

In general all Graphs-related plotting functions are not supported for now. Please, check [this page](https://jerryi.github.io/wljs-docs/frontend/Reference/Plotting%20Functions/ArrayPlot) (`Plotting function` section), where we listed all tested functions (there are probably more...). Since Wolfram Language uses higher-order function, that produce low-level `Graphics` primitives with million options used, we can't really say in advance which is going to work correctly and which isnt. In this sense, feel free to post anything you found working incorrectly to Issues. Then we can also know how to distribute our attention as developers.  

Since you requested `Graphs` here, we will try to fix it 😀 
In principle, Graphs relies on `Graphics` primitives, which are mostly implemented. We need to work a bit on converting Mathematica's boxes to our format.

**Comment by JerryI** [comment]
I see, an issue mostly connected with `Arrow` function

<img width="603" alt="Screenshot 2024-05-01 at 22 14 28" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/39f521ce-ea84-46d4-8419-df4299b39d3a">

**Comment by gdelfino** [comment]
Thanks for your quick answer and your effort developing this project. Yes, I noticed that `Graph` is not supported yet. That is why I tried `GraphPlot` which returns a `Graphics` instead of a `Graph`.

For the future, maybe graphs could be rendered using https://github.com/DerYeger/yeger/tree/main/packages/d3-graph-controller

**Comment by JerryI** [comment]
Kinda works now. I rewrote some primitives of `Graphics` package and rewrote `MakeBoxes` definition to apply `GraphPlot` to any `Graph` symbol on output. Works as a syntax sugar, the inner expression is still the same.

![Screenshot 2024-05-03 at 18 53 25](https://github.com/JerryI/wolfram-js-frontend/assets/4111822/7e35acb6-6913-45b5-9171-418fc31d2123)

I checked some of examples from WM refs page

PS: To get new version click on `Check Updates` in settings menu. On the next startup it will fetch and install them.
