### ISSUE TITLE
Support for Neural Networks output

### ISSUE THREAD

**Issue by s4m13337** [JerryI/wolfram-js-frontend#186]
It would be interesting to have support for neural network structure/graph output. Currently it just displays a tiny blank box. 

Also when training the network with, no helpful information is displayed regarding the current status of training. If TrainingProgressReporting -> "Print" is set, then the information appears on the information bubble on the top right, which is not very useful. It would be easier to track if it gets printed on to the cell.

I hope this gets implemented in the near future as this would really accelerate my research work with neural networks.

**Comment by JerryI** [comment]
We tried our best, however, the developers of WL encoded the output form in somewhat complicated way, so that we are not able to overwrite the definitions of `StandardForm` for things such as `LinearLayer` and etc. Another option, we can still introduce a wrapper expressions for each problematic symbol. It wont' affect the evaluation process and UX, but will help to get informative output. Writing an output wrapper symbol is a bit cumbersome,  therefore we ask for your help.

Could, you, please mention the *most essential* or required for your typical neural network workflow object symbols? There are too many of them to check. Ones I found are used mostly (represent the state)

- `LinearLayer` probably other layers as well
- `NetChain`
- `NetEncoder`
- `NetDecoder`

**Comment by JerryI** [comment]
https://github.com/user-attachments/assets/f63ed84a-259c-4d8b-a1e8-6152bc774c43

New release
