### ISSUE TITLE
Frontend distorts images' colours.

### ISSUE THREAD

**Issue by gabpedroza** [JerryI/wolfram-js-frontend#221]
**Describe the bug**
Whenever I generate an image with Wolfram, it comes out with its colours distorted, as if some dark mode utility tried to adapt it to dark mode.

**To Reproduce**
I tried running the following code:
`Graphics3D[{{Red, N@PolyhedronData["Spikey", "Polygons"]}}, 
  Boxed->False,"RTX"->True,"Lighting"->None,
  ImageSize->{500, 400},"ViewProjection"->"Perspective", 
  "Lightmap"->"https://raw.githubusercontent.com/JerryI/Mathematica-ThreeJS-graphics-engine/master/assets/PureSky.hdr"
]` in a completely new notebook. I tested with both vanilla settings, "remove windows 11 vibrancy" enabled/disabled and "inner window transparency" enabled/disabled. I also tried running on the browser, with and without my dark mode extension enabled. Also, I have found this bug only happens with Windows 11 dark mode enabled.

**Expected behavior**
I expected it to generate the image seen [here](https://community.wolfram.com//c/portal/getImageAttachment?filename=22.png&userId=937303)

**Screenshots**
![image](https://github.com/JerryI/wolfram-js-frontend/assets/172933533/a29d2e21-2e35-4aad-acdf-e3252ba4637a)

**Desktop (please complete the following information):**
 - OS: Windows 11 with dark mode enabled.
 - Browser = chrome AND latest desktop app (2.4.2).

**Comment by JerryI** [comment]
Hi @gabpedroza,
This is not a bug, but rather the disadvantage of implementation of dark mode. We aren’t good at UI design, so it is just a filter applied to all view, which inverts colors and corrects a hue.

**Comment by gabpedroza** [comment]
Hi @JerryI !!

Thank you for the speedy answer! Is there anyway that I can disable dark mode for WLJS Frontend? I really don't have a problem with it being in light mode, though I'd like to keep using the rest of my PC in dark mode.

**Comment by JerryI** [comment]
It did not, now it does ;), but only in Desktop App version.
Please fetch an updated binary from [here](https://github.com/JerryI/wolfram-js-frontend/releases/download/2.4.2/WLJS.Notebook.Setup.2.4.4.Minimal.exe). Then, you can click `Reinstall` on a launcher window, it will install a new version (we did not increase the version number, so that those minor changes won't bother other users).

**Comment by JerryI** [comment]
Here how it looks like

<img width="319" alt="Screenshot 2024-06-28 at 20 20 58" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/38ee5b44-97ac-42b3-8125-bddbe8dafb2d">

it requires a restart to see changes. 
If it is opened from a regular browser, we don't have much control over `dark` or `light` modes, since it uses preferences from your browser provided as CSS media requests. We could move this responsibility to Javascript with additional CSS classes, however, some initial tests did show flickering issues on Unix machines (when JS loaded a bit later, it switches dark/light mode with a small delay)

**Comment by gabpedroza** [comment]
@JerryI , it works!!!!! Thank you very much, you rock!
