### ISSUE TITLE
Unicode Glyph does not display

### ISSUE THREAD

**Issue by Suzukazole** [JerryI/wolfram-js-frontend#260]
# Issue 
The output cell displays the actual Unicode instead of the glyph. Is there a way to get the Glyph to appear correctly?

# Steps to Reproduce
Evaluating this expression:
`Series[(*FB[*)((2I)(*,*)/(*,*)(\[Pi]^2 x))(*]FB*) BesselK[1, x^2], {x, 0, 2}]`

Yields
![image](https://github.com/user-attachments/assets/96dc562d-5be8-4b5c-8adb-7128f8ffb1d8)

Where the Unicode glyphs for `\[ImaginaryI] `and `\[Pi]` are displayed as the actual code instead.

## Version
- Wolfram Engine 14.0.0 
- WLJS Version 2.5.0 run as AppImage
- Output of `$SystemID` : `"Linux-x86-64"`

**Comment by JerryI** [comment]
Correct. This is indeed a bug of some wrapper boxes.
As a temporal solution, request `Normal` form

![Screenshot 2024-08-01 at 15 19 41](https://github.com/user-attachments/assets/1352c5c4-7229-47b6-84fa-0174cff7bd47)

**Comment by JerryI** [comment]
<img width="654" alt="Screenshot 2024-08-03 at 13 13 22" src="https://github.com/user-attachments/assets/20ba88ae-0a3f-4f7f-96e5-38e358b24716">


Fixed with regular expressions in a new release of `wljs-editor`. It is not great, but this is a big pain on how WL handles encoding and switches back and forth between `\[Pi]` and a real Pi unicode symbol. We will find more general solution on that.

To force update (usually takes 3 days interval to check automatically) locate in the settings a button `Check Updates` and then restart an app.
