### ISSUE TITLE
Ctrl+w does not close tabs in the browser 

### ISSUE THREAD

**Issue by zvnkk** [JerryI/wolfram-js-frontend#302]
Once i start wljs and use brave browser or something else ctrl+w does not work any more,  tabs are not being closed, does not matter what website i have open, is it loclahost or not .
Once i close wljs from system tray ctrl + w starts work again.
there should be some remap set for ctrl +w somewhere, but i can't find it

**Comment by JerryI** [comment]
Correct, this is a bug. Instead of a local shotcut a [global one was registered](https://github.com/JerryI/wolfram-js-frontend/blob/78ad5fd669af81f387b356c97ba8d8a975e3438a/Electron/main.js#L1640)

You can entirely bypass electron by running `start.wls` from your `App Data/wljs-notebook/Scripts` folder or cloned repository. As a drawback, an association with file extensions will no longer work as well as updates (unless you do manually `git pull`)

We will fix this in the next release.

**Comment by JerryI** [comment]
Which OS are you using?

**Comment by JerryI** [comment]
I assume probably windows.
Here is a [new binary](https://github.com/JerryI/wolfram-js-frontend/releases/download/2.5.8/wljs-notebook-2.5.9-x64.exe)

if linux [here](https://github.com/JerryI/wolfram-js-frontend/releases/download/2.5.8/wljs-notebook-2.5.9-amd64.deb) is another one

**Comment by zvnkk** [comment]
I'm on windows, installed new binary and ctrl+w works as expected, thanks for quick fixes 🔥
