### ISSUE TITLE
Can't start evaluation Kernel on Windows (Timeout error)

### ISSUE THREAD

**Issue by amindanial** [JerryI/wolfram-js-frontend#310]
I have Wolfram Engine:
14.0.0 for Microsoft Windows (64-bit) (December 21, 2023)
Windows-x86-64

During the starting of the WLJS notebook it connects with the Engine, whenever the notebook begins it gives timeout and no command is executed. 
![Screenshot 2024-11-24 135045](https://github.com/user-attachments/assets/71391c47-53d4-4f1d-b5d4-7ee7aa22f1c8)
![Screenshot 2024-11-24 135118](https://github.com/user-attachments/assets/0cb636fe-3bb2-4a8a-938a-6693cf30fb68)

**Comment by JerryI** [comment]
Most probably you don't have any WolframEngine instances running.
Please, check a task manager, if you see Wolfram Kernel process running if WLJS App is closed. It might a common issue caused by the standard license limitation for 2 processes.

If not, there might be another bug with WE.
I have seen it on 1 Windows 10 machine, that you need to disconnect from the internet before starting an App, and then when it started and there is no sign of `Timeout`, you can connect back to the network and work normally. I really hope this is not the case for all win10 + Wolfram Engine 14...

**Comment by JerryI** [comment]
Please, reopen if the problem is still there
