### ISSUE TITLE
Output of a list of one association holding several TimeSeries is too verbose 

### ISSUE THREAD

**Issue by Hachann** [JerryI/wolfram-js-frontend#313]
Hello guys,

If you run this command in WLJS you end up with a very verbose output and an "Too long to display" message : 

`{<|"a" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "b" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "c" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "a" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "d" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "e" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "f" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "g" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "h" -> TimeSeries[RandomVariate[NormalDistribution[],10]], "i" -> TimeSeries[RandomVariate[NormalDistribution[],10]] |>}`

If you run it in Mathematica, it outputs a short list of TimeSeries objects in an Association, which is not that long :

![image](https://github.com/user-attachments/assets/79c27464-7381-4e2e-82e6-212afff61a6b)

**Comment by JerryI** [comment]
It is always a compromise, if you need a richer output or less laggy editor. If you don't plan to edit an output expression, one can just set [$OutputCharactersLimit](https://jerryi.github.io/wljs-docs/frontend/Reference/Decorations/$OutputCharactersLimit)

**Comment by JerryI** [comment]
After a certain limit those boxes will be converted to references and and an output will be shown, since the data will no long be inside a notebook cell

```wolfram
{<|"a" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "b" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "c" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "a" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "d" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "e" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "f" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "g" -> TimeSeries[RandomVariate[NormalDistribution[],200]], "h" -> TimeSeries[RandomVariate[NormalDistribution[],200]]|>}
```

**Comment by Hachann** [comment]
Thank you for your kind answer.

I understand that editing the output is a plus over Mathematica notebook, but if more people are like me, then I think some users do not need this feature, especially if they are regular Mathematica user. The output is what is most desired, and we struggle to write the best input possible to compute the desired outcome.

Maybe offer the possibility in Preferences to make the output editable or not ? So that makes it trivial : if not enabled, the output should be approximately the same as in Mathematica ?

**Comment by JerryI** [comment]
> Thank you for your kind answer.
> 
> 
> 
> I understand that editing the output is a plus over Mathematica notebook, but if more people are like me, then I think some users do not need this feature, especially if they are regular Mathematica user. The output is what is mostly desired, and we struggle to write the best input possible to compute the desired outcome.
> 
> 
> 
> Maybe offer the possibility in Preferences to make the output editable or not ? So that makes it trivial : if not enabled, the output should be approximately the same as in Mathematica ?

In principle it does not matter, if the output is editable or not, the rendering is a problem, which can hand the whole notebook for seconds or minutes. And it is dangerous for UX.

Mathematica does it in a tricky way, it is a sort of a preview until you click on the output cell and then it is converted to a normal one. We could try to do it in a similar way instead of showing "output is too long". However it is question how to trim it properly or transform to have less impart on the editor.

For now I can suggest to make an option in the preferences which globally overrides the maximum output length, so one can set it once to your preferred value.

**Comment by JerryI** [comment]
Added in this [commit](https://github.com/JerryI/wljs-editor/commit/cff01366a900f9adf0b80fb3ddab9ea01dbec156)

![Screenshot 2024-11-29 at 15 18 49](https://github.com/user-attachments/assets/a0e03f92-5f98-418e-b4bf-b785f0b228ad)

**Comment by JerryI** [comment]
I would keep this as an `enhancement` issue, since most troubles comes from the way, how `wljs-editor` handles such widgets with inline data. 

We rely heavily on recursive RegExp to find and hide the data from such objects like `TimeSeries`, which at some symbols combination involves a lot of backtracking. The editor itself can handle much more characters, however at some particular cases the parser struggles more, therefore we set a "safe" limit of 5000, which was tested on relatively slow machines from 2013.

However, those things can be improved, I am sure.

**Comment by JerryI** [comment]
We made some improvements. Now it is similar to what mathematica does

for example, I have a huge table with tons of decorations

```mathematica
Pane[
  TableForm[
    {#[[1]], If[#[[2]] < 5000.0, Item[#[[2]], Background->Hue[Sin[#[[2]]] // Abs]], #[[2]]]} &
  /@ RandomReal[{0,10000}, {200, 2}], 
   TableHeadings -> {
     Table[StringTemplate["Group ``"][i], {i, 200}], 
     {"y1", "y2"}}
  ]
, {500,300}]
```

it gives me a choice

![Screenshot 2024-12-17 at 21 02 40](https://github.com/user-attachments/assets/ef543f6f-472c-47f7-b78f-07f22706cbb6)

If you click `Show anyway`, it will render it fully (but, don't try to edit ;D)

![Screenshot 2024-12-17 at 21 03 16](https://github.com/user-attachments/assets/bc5255bd-da4b-48b2-bcd5-8f088bfd26a6)

You can scroll though, it will progressively render the lines. Once fully loaded it will scroll with no lag.
