### ISSUE TITLE
PlotTheme "unknown WL expression."

### ISSUE THREAD

**Issue by limaaii** [JerryI/wolfram-js-frontend#324]
Doing this simple plot available at the Wolfram Documentation Center ( https://reference.wolfram.com/language/ref/PlotTheme.html)
![image](https://github.com/user-attachments/assets/0648e9e8-29e4-4da0-9414-feeee277968a)
Works without the PlotTheme
![image](https://github.com/user-attachments/assets/a2e2ea37-1b94-42ba-a472-681d36ebde1f)
It is working fine on Jupyter, on the same machine and engine.
![image](https://github.com/user-attachments/assets/d16368a8-8bd4-4f3e-ae34-f1fd92b3d630)

**Comment by JerryI** [comment]
Fixed in [#commit](https://github.com/JerryI/wljs-graphics-d3/commit/ac40935cb721c9a9c2d9b38432e42a4d3c4b895c). 

`AbsoluteDashing` was not implemented. Now we added its support to most 2D primitives :)

<img width="506" alt="Screenshot 2024-12-29 at 11 02 39" src="https://github.com/user-attachments/assets/03ffb5d2-3364-4939-84c6-75244960a52d" />

You will get an updated version in 2-3 days, but you can force to download a new module by clicking `Check updates` from the menu. On the restart it will be installed.

---

It's hard to compare with Jupyter, since in the implementation of Wolfram J Kernel there it basically rasterizes any output to an image, while in WLJS we render graphics, equations, sound, video in place by executing one by one underlying WL expressions. Therefore some parts we could just missed like here `AbsoluteDashing` symbol used in a monochrome theme.
