### ISSUE TITLE
JS Console: `method destroy is not defined for Association`

### ISSUE THREAD

**Issue by walking-octopus** [JerryI/wolfram-js-frontend#62]
Every time a notebook with a graph is ran, the error above appears.

Wolfram Engine 13.3.
Git commit [122a577](https://github.com/JerryI/wolfram-js-frontend/commit/122a5770c0d0512277e11e0cc7e76a5617a3826d).

---

Also, I know this is not the appropriate place to post this, but I just wanted to thank you for making this project! I'm just an occasional user of Mathematica and I couldn't reconcile the beauty of the language with the painful official notebook UI, let alone the pricing. Thanks to your projects I can now iterate faster on my models with all the proper graphing, autocomplete and math rendering of a proper Wolfram notebook app. I can't thank you enough for this! If only you could re-implement the entire interpreter too to get rid of the bloat there, but I suppose most power users need too much of Wolfram even a perfect re-implementation without some of STD will be useless.

**Comment by JerryI** [comment]
This is definitely a proper place for such issues 🥇 
I very glad to hear your feedback. Thank you for your warm words ❤️

You can also post it on our [telegram channel](https://t.me/+PBotB9UJw-hiZDEy)  if you wish.

An error message you mentioned actually can be considered as warning message, it is not harmful at all.
The idea is, that sometimes dynamic symbols are evaluated on the frontend, which has to be disposed properly to exclude memory leaks and any hanging event-handlers. When a cell got destroyed, WLJS interpreter goes through the whole tree of expressions and apply `.destroy` methods. Since this mechanism came up quite late, I just did not manage to encounter all cases when a function hits `.destroy()` ;)

Feel free to post issues on anything you encounter and as often as you prefer. We (@KirillBelovTest and me) try our best to help you and other people. 

Totally agree with WL and STD! And also there are too many hassle with licensing, activating, especially on M1/M2 processors, differences in LibraryLink implementation from version to version makes me wish that someone could release an independent interpreter. 

PS: Please check `Reference` section on [docs page](https://jerryi.github.io/wljs-docs/docs/frontend/Reference/Plotting/BarChart) for graphics and plotting function, which are tested. Actually, there are still many features missing (not much stuff for 3D graphics/plots). However, it is relatively easy to add them to the current system and it is mostly a question of time.

**Comment by JerryI** [comment]
Fixed in [Commit](https://github.com/JerryI/wljs-interpreter/commit/95cfd859d53969de5e218b8e6bf04aa87ce70fa4)

On the next startup WLJS Notebook will update this component automatically.
