### ISSUE TITLE
Colors don't work

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#68]
Graphics appear in grey, black, or white (depending on light mode or dark mode and depending on if you call for a color in the code).

Is this a bug on my end, or something that's just not yet supported?

**Comment by JerryI** [comment]
Could you, please, share an example code or notebook or a screenshot that demonstrates the problem?

**Comment by LoganJFisher** [comment]
![0buVQbL](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/824f7696-ab49-4285-982d-4c0163806528)

**Comment by JerryI** [comment]
Thanks! The implementation of `Graphics3D` is in general much worse compared to `Graphics`. However, fundamentally it is relatively easy to add new features to fill the gap between Mathematica and WLJS.

The problem was, that `VextexColors` option provided in `GraphicsComplex` was ignored by 3D engine. I fixed it in [this commit](https://github.com/JerryI/Mathematica-ThreeJS-graphics-engine/commit/b9a4f7c1d4f5a8cb1bbb33102b7979cd193402f2#diff-145dba11b4d975204550e1e4185ed515d3d1824378c6dc5e8d26df534b92a396) (src/kernel.js)
![screenshot](https://github.com/JerryI/wolfram-js-frontend/assets/4111822/a68b21dc-99a8-4d0f-9f9b-3cd7ea2217d0)


After restart frontend will fetch a new version automatically. If the result is the same, you can try `Window -> Force Reload` to reset JS cache.

**Comment by LoganJFisher** [comment]
Thank you. That fixed it.

I'm also having an issue with normal Plot, but I'll make a new issue report for that.
